name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure build
        run: cmake --preset linux
      - name: Build
        run: cmake --build --preset linux -j
      - name: Test
        run: ctest --preset linux
